server:
  port: 8080

spring:
  application:
    name: lan-recruitment-backend
  datasource:
    url: jdbc:mysql://localhost:3306/lan_recruitment?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initialization-fail-timeout: -1
  profiles:
    active: dev

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

sa-token:
  token-name: satoken
  timeout: 2592000
  active-timeout: -1
  is-concurrent: true
  is-share: true
  token-style: uuid

email:
  host:
  from:
  password:
  username:
